# Site settings
title: David Le
email: davidhle@gatech.edu
url: https://davidhle.com
description: "Student, Developer, & Designer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#219ab3'
  navbar: '#051c42'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/david-le-9b0b45102/
  - title: github
    url: https://www.github.com/davidhle/
  - title: instagram
    url: https://www.instagram.com/thedavidle/
  - title: behance
    url: https://www.behance.net/davidhle0f49

# Build settings
markdown: kramdown
permalink: pretty
